var dataset = [
	[
		{
			"id":"scenario-0",
			"text":"<p>The election is just around the corner. It’s all you and your collegemates are talking about!</p><p>Having just turned 18, it’ll be your first time voting. You cannot be more excited to exercise your right as a citizen.</p>",
			"img":"../img/story-0/1.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Next",
			"target0":"scenario-0_1",
		},
		{
			"id":"scenario-0_1",
			"text":"<p>You’re also very anxious as voting is a big responsibility, but you just don’t know who you’ll be voting for! You ask your friends. After all, they usually share the same opinions and worry about the same things.</p>",
			"img":"../img/story-0/1.svg",
			"more":1,
			"info":"<p>Have you heard of Groupthink Bias or Social Bubble?</p><p>Groupthink is when you find yourself forming opinions based on what the majority thinks, or not wanting to disagree with them.</p><p>A Social bubble is when you find yourself mostly conversing with a select group of people who usually share them same views as you, leading to an echo chamber when you are not exposed to other point of views.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Chances are, you’ll all be voting the same way, right? Right?",
			"target0":"scenario-0_2",
		},
		{
			"id":"scenario-0_2",
			"text":"<p>They tell you they'll likely vote for this young, upcoming lawmaker Siti Yasmin who is wildly popular on TikTok. You follow this politician's account too.</p>",
			"img":"../img/story-0/2.svg",
			"more":1,
			"info":"<p>Did you know that social media platforms like TikTok are slowly replacing Google as a search engine for young people? This means more and more folks rely on social media as a source of information, even news. The problem with this is could lead to spread of unverified or one-sided information and fake news.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Next",
			"target0":"scenario-0_3",
		},
		{
			"id":"scenario-0_3",
			"text":"<p>You watch the latest videos the candidate recently uploaded.</p><p>In it, Siti Yasmin warns her followers and constituents against voting for her rival, a veteran politico and seat incumbent S.Jega, who she claims is very conservative and traditional. Voting for him, she warns, can result in a lack of freedom and rights for today’s youth.</p>",
			"img":"../img/story-0/2.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"That's scary!",
			"target0":"scenario-0_4",
		},
		{
			"id":"scenario-0_4",
			"text":"<p>What do you do next?</p>",
			"img1":"../img/story-0/3a.svg",
			"img2":"../img/story-0/3b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Nothing!",
			"target0":"scenario-A",
			"opt1":"Gather more info on both candidates",
			"target1":"scenario-B",
		},
		{
			"id":"scenario-A",
			"text":"<p>The more you follow her, the more you like her. She’s young and cool and up with the times! She's sure to be a good YB!</p>",
			"img":"../img/story-0/4.svg",
			"more":1,
			"info":"<p>Introducing the Halo/Horn Effect</p><p>Almost all of us are guilty of making snap judgements against someone, causing us to like/not like them.</p><p>The halo effect is a bias that causes us to like a person based on one believed positive trait while ignoring all the bad. The horn effect is the opposite, where we view a person negatively based on one perceived bad trait/stereotype. This could lead us to ignore any good trait that person might have.</p><p>An example of this is assuming good-looking people are competent, young people as progressive, or certain groups of people are lazy.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Next",
			"target0":"scenario-A_1",
		},
		{
			"id":"scenario-A_1",
			"text":"<p>You relate to her more than that other lawmaker who's about the same age as your dad. Plus, she seems to be saying all the right things.</p>",
			"img":"../img/story-0/4.svg",
			"more":1,
			"info":"<p>Do you know what Confirmation Bias is?</p><p>It's when you believe news just because it strengthens what you already believe in or value, without knowing if the information is true or not. For example, good news about your favourite football player or bad news about vaccines if you're an anti-vaxxer.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"So why even consider anyone else?",
			"target0":"scenario-A_2",
		},
		{
			"id":"scenario-A_2",
			"text":"<p>Come election day, you're about to head to your polling station when you receive a text message.</p><p>A classmate tells you about a rumour he's heard about the rival candidate, but thinks the latter is being framed.</p>",
			"img":"../img/story-0/5.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"What's your next move?",
			"target0":"scenario-A_3",
		},		
		{
			"id":"scenario-A_3",
			"text":"",
			"img1":"../img/story-0/6a.svg",
			"img2":"../img/story-0/6b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Ignore it lah!",
			"target0":"scenario-A1",
			"opt1":"Fact check!",
			"target1":"scenario-B1-2",
		},
		{
			"id":"scenario-A1",
			"text":"<p>This changes nothing. After all, this only reaffirms your belief she is the best candidate.</p>",
			"img":"../img/story-0/4.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Time to vote!",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-A1_1",
			"text":"<p>You end up voting for Yasmin, your TikTok politico candidate.</p><p>Not long after, to your dismay, she begins backtracking on all her pledges and, worse, goes after critics, including your friends, and tries to silence them!</p>",
			"img":"../img/story-0/7.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"No!",
			"target0":"scenario-A1_2",
		},		
		{
			"id":"scenario-A1_2",
			"text":"<p>You can't help but wonder if there'd been warning signs you missed. Perhaps, had you done more research, you wouldn't have been so easily swayed by her propaganda and election promises?</p>",
			"img":"../img/story-0/7.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"The end",
			"target0":"scenario-end",
		},	
		{
			"id":"scenario-B",
			"text":"After all, she seems too good to be true. Doesn't hurt to consider all options.",
			"img":"../img/story-0/5.svg",
			"more":1,
			"info":"<p>When something you read or someone says sounds too good to be true, it sometimes can be. You should try to vet information or seek to learn more about an issue/claim/candidate/their party before committing to an opinion.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"How to gather info?",
			"target0":"scenario-B_1",
		},	
		{
			"id":"scenario-B_1",
			"text":"",
			"img1":"../img/story-0/8a.svg",
			"img2":"../img/story-0/8b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"The Internet and social media, of course!",
			"target0":"scenario-B1",
			"opt1":"Talk to people!",
			"target1":"scenario-B2",
		},		
		{
			"id":"scenario-B1",
			"text":"What do you find?",
			"img1":"../img/story-0/9a.svg",
			"img2":"../img/story-0/9b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Who would've thought?",
			"target0":"scenario-B1-1",
			"opt1":"Dirt!",
			"target1":"scenario-B1-2",
		},
		{
			"id":"scenario-B1-1",
			"text":"<p>Jega makes a lot of good points. His manifesto on addressing youth unemployment seems promising. Perhaps he isn't as out of touch as you assumed. You realise that the first candidate isn't as perfect as she seems and has been misrepresenting her rival.</p>",
			"img":"../img/story-0/10.svg",
			"more":1,
			"info":"<p>See what you did? By researching and listening to other people’s perspective, you are able to get out of your echo chamber, recognise your own bias that could have blinded you to misinformation and propaganda, and influenced your vote.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Time to vote!",
			"target0":"scenario-B1-1_1",
		},
		{
			"id":"scenario-B1-1_1",
			"text":"<p>You end up voting for Jega. Not long after, you read about how Yasmin — the TikTok candidate you initially favoured. She begins backtracking on all her pledges and, worse, goes after critics, including your friends, and tries to silence them!</p>",
			"img":"../img/story-0/11.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"The end",
			"target0":"scenario-end",
		},	
		{
			"id":"scenario-B1-2",
			"text":"<p>As you begin looking up the second candidate, S. Jega, your social media feed becomes inundated with posts attacking him. The posts, while appearing to come from different individuals, all seem to say the same thing. They accuse him of corruption in the past, although none provides proof.</p>",
			"img":"../img/story-0/12.svg",
			"more":1,
			"info":"<p>Uh-oh, Cybertroopers</p><p>Cybertroopers are people who are paid to spread political propaganda/ fake news on the internet and attack specific people online.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Hmm...",
			"target0":"scenario-B1-2_1",
		},
		{
			"id":"scenario-B1-2_1",
			"text":"<p>Jega denies the claims and says he's a victim of a smear campaign from the opposition party to scare voters.</p>",
			"img":"../img/story-0/12.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Who do you believe?",
			"target0":"scenario-B1-2_2",
		},
		{
			"id":"scenario-B1-2_2",
			"text":"",
			"img1":"../img/story-0/13a.svg",
			"img2":"../img/story-0/13b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Jega",
			"target0":"scenario-B1-2-1",
			"opt1":"The rumours",
			"target1":"scenario-B1-2-2",
		},
		{
			"id":"scenario-B1-2-1",
			"text":"<p>You give him the benefit of the doubt. After all, none of the accusers provides any proof. You decide to do some digging! You search for any information on this alleged corruption incident and come across several old news reports.</p>",
			"img":"../img/story-0/14.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Wait a minute!",
			"target0":"scenario-B1-2-1_1",
		},
		{
			"id":"scenario-B1-2-1_1",
			"text":"<p>Some of the news reports that disparage him are from portals you've never heard of before or are affiliated with the party of the TikTok politician. Meanwhile, you find other old news reports of police already clearing Jega of any wrongdoing.</p>",
			"img":"../img/story-0/15.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Time to vote!",
			"target0":"scenario-B1-1_1",
		},
		{
			"id":"scenario-B1-2-2",
			"text":"<p>You start having doubts over this candidate's credibility. After all, why would so many people repeat the same accusation if it isn't true?</p>",
			"img":"../img/story-0/16.svg",
			"more":1,
			"info":"<p>Have you heard of Groupthink Bias or Social Bubble?</p><p>Groupthink is when you find yourself forming opinions based on what the majority thinks, or not wanting to disagree with them.</p><p>A Social bubble is when you find yourself mostly conversing with a select group of people who usually share them same views as you, leading to an echo chamber when you are not exposed to other point of views.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"The majority cannot be wrong, right?",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-B2",
			"text":"<p>It helps to seek the opinion of people beyond like-minded friends. Surprisingly, not everyone's convinced by your now-favourite candidate. Your non-Malay classmates find some of her videos exaggerated and racist.</p>",
			"img":"../img/story-0/17.svg",
			"more":1,
			"info":"<p>See what you did? By researching and listening to other people’s perspective, you are able to get out of your echo chamber, recognise your own bias that could have blinded you to misinformation and propaganda, and influenced your vote.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Interesting...",
			"target0":"scenario-B2_1",
		},
		{
			"id":"scenario-B2_1",
			"text":"<p>Others say the rival, Jega, has a proven track record of serving his constituents. They also point out news articles in which Yasmin maligns Jega by playing up stereotypes and racial views.</p>",
			"img":"../img/story-0/18.svg",
			"more":1,
			"info":"<p>Don't be fooled by racial politics!</p><p>Racial or extreme politics is the use of race or other issues by politicos to divide voters or the public.</p><p>This is used by politicians to pit one race/group against another for their political gain, or to distract from other issues.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"That's new to me",
			"target0":"scenario-B2_2",
		},
		{
			"id":"scenario-B2_2",
			"text":"<p>She even says that a vote for Jega is unpatriotic and will mean you stand against your entire race and community.</p>",
			"img":"../img/story-0/18.svg",
			"more":1,
			"info":"<p>Infobox: Did you hear about False Dichotomy/False Binary?</p><p>Sometimes called the 'either/or' thinking, it's when a person is presented with just two choices/ sides when in fact, there are often more sides/options to choose from.</p><p>For example, a person might tell you that if you disagree with one government policy, you are against the whole government, or if you disagree with one woman candidate, you are an anti-feminist.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"How now brown cow?",
			"target0":"scenario-B2_3",
		},
		{
			"id":"scenario-B2_3",
			"text":"",
			"img1":"../img/story-0/19a.svg",
			"img2":"../img/story-0/19b.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"You stick to your gut",
			"target0":"scenario-B2-1",
			"opt1":"Look for more info on rival candidate",
			"target1":"scenario-B1-1",
		},
		{
			"id":"scenario-B2-1",
			"text":"<p>Yasmin seems to be exactly what the doctor ordered. After all, majority of your own circle of friends are fans. Looks like she’s the candidate to beat. The majority cannot be wrong. If she turns out to be a bum lawmaker, you can always vote her out at the next election.</p>",
			"img":"../img/story-0/20.svg",
			"more":1,
			"info":"<p>Have you heard of Groupthink Bias or Social Bubble?</p><p>Groupthink is when you find yourself forming opinions based on what the majority thinks, or not wanting to disagree with them.</p><p>A Social bubble is when you find yourself mostly conversing with a select group of people who usually share them same views as you, leading to an echo chamber when you are not exposed to other point of views.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Time to vote!",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-end",
			"text":"<p>It is the right of every citizen to vote come election time! But it isn't always easy, what with the amount of propaganda, fake news and other tricks waiting to deceive voters. To make things worse, our own biases (we all have them!) can sometimes get in the way of us making the right choice. Learning to identify political and divisive propaganda, misinformation and bias can help you take charge and make an informed choice that's most beneficial to you and country.</p>",
			"endLinks":[
				"<a href='https://www.youtube.com/watch?v=Jqt7B857ooM' target='_blank'>The Vaccine for Fake News</a>",
				"<a href='https://sea.mashable.com/tech/20996/for-gen-z-tiktok-is-more-than-entertainment-its-a-search-engine' target='_blank'>For Gen Z, TikTok is more than entertainment. It's a search engine.</a>",
				"<a href='https://www.malaymail.com/news/malaysia/2021/01/14/report-malaysian-cybertrooper-teams-employ-full-time-staff-used-by-politici/1940305' target='_blank'>Report: Malaysian cybertrooper teams employ full-time staff, used by politicians and businesses alike</a>",
				"<a href='https://inoculation.science/inoculation-videos/' target='_blank'>Short videos that inoculate against misinformation online</a>",
			]
		}
	]	
];