var dataset = [
	[
		{
			"id":"scenario-0",
			"text":"<p>Hari mengundi sudah dekat. Setiap hari, anda dan rakan-rakan sekuliah tidak habis-habis berbincang soal ini.</p><p>Baru menginjak usia 18 tahun, ini kali pertama anda akan mengundi. Teruja betul rasanya untuk melaksanakan hak anda sebagai warganegara.</p>",
			"img":"../img/story-0/1.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Seterusnya!",
			"target0":"scenario-0_1",
		},
		{
			"id":"scenario-0_1",
			"text":"<p>Anda juga berdebar - mengundi itu kan satu amanah besar. Hendak pilih siapa pun anda tidak tahu! Anda bertanya kepada rakan-rakan, namun mereka pun seperti anda juga, bimbang akan hal yang serupa.</p>",
			"img":"../img/story-0/1.svg",
			"more":1,
			"info":"<p>Pernahkah anda dengar tentang Bias Mengikut Kumpulan atau Gelembung Sosial?</p><p>Bias mengikut kumpulan adalah apabila anda membentuk pendirian berdasarkan pandangan majoriti, atau tidak mahu berlawanan pendirian dengan mereka.</p><p>Gelembung sosial pula adalah apabila anda berinteraksi hanya dengan sekumpulan orang tertentu yang selalunya berkongsi pendirian serupa dengan anda. Ini membawa kepada 'ruang gema' apabila anda terdedah hanya kepada pandangan serupa, dan tidak terdedah kepada sudut pandang dan pendirian lain.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Korang pun akan mengundi macam ni juga, kan?",
			"target0":"scenario-0_2",
		},
		{
			"id":"scenario-0_2",
			"text":"<p>Kata mereka, mereka mungkin akan mengundi calon muda, Siti Yasmin yang sangat popular di TikTok. Anda pun turut mengikuti akaun ahli politik tersebut.</p>",
			"img":"../img/story-0/2.svg",
			"more":1,
			"info":"<p>Tahukah anda bahawa platform media sosial seperti TikTok sedikit demi sedikit semakin menggantikan Google sebagai enjin carian buat orang muda? Maknanya, semakin ramai yang bergantung pada media sosial sebagai sumber maklumat dan berita. Masalahnya, ini boleh membawa kepada penyebaran berita palsu dan maklumat tidak sahih atau berat sebelah.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya!",
			"target0":"scenario-0_3",
		},
		{
			"id":"scenario-0_3",
			"text":"<p>Anda tonton video terbaharu Siti Yasmin.</p><p>Dia memberi amaran kepada para pengikutnya agar jangan mengundi calon lawan, ahli politik veteran yang juga penyandang kerusi, S.Jega. Dakwanya, pesaingnya itu sangat konservatif dan mengikut cara lama. Tegasnya lagi, mengundi Jega akan menyebabkan kurangnya kebebasan dan hak untuk belia.</p>",
			"img":"../img/story-0/2.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Takutnya! ",
			"target0":"scenario-0_4",
		},
		{
			"id":"scenario-0_4",
			"text":"<p>Apa nak buat selepas ini?</p>",
			"img1":"../img/story-0/3a-my.svg",
			"img2":"../img/story-0/3b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Tiada apa-apa! ",
			"target0":"scenario-A",
			"opt1":"Dapatkan lebih banyak maklumat tentang kedua-dua calon.",
			"target1":"scenario-B",
		},
		{
			"id":"scenario-A",
			"text":"<p>Semakin lama, anda semakin menyukainya. Dia muda, cool dan mengikut peredaran masa. Dia pasti akan menjadi YB yang baik!</p>",
			"img":"../img/story-0/4.svg",
			"more":1,
			"info":"<p>Memperkenalkan Kesan Halo/Tanduk</p><p>Hampir setiap daripada kita pernah menghakimi seseorang secara sekilas, menyebabkan kita berasa suka atau tidak suka kepadanya.</p><p>Kesan halo adalah bias yang menyebabkan kita suka kepada seseorang berdasarkan satu ciri positif yang kita percayai,  sementara mengabaikan ciri buruk yang lain. Kesan tanduk pula adalah sebaliknya, apabila kita melihat seseorang secara negatif berdasarkan satu ciri buruk/stereotaip. Ini boleh menyebabkan kita mengabaikan sebarang ciri baik yang dimiliki seseorang.</p><p>Contohnya, menganggap orang-orang yang elok rupa paras sebagai cekap, orang-orang muda sebagai progresif, atau kumpulan-kumpulan tertentu sebagai malas.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya!",
			"target0":"scenario-A_1",
		},
		{
			"id":"scenario-A_1",
			"text":"<p>Anda rasa lebih sefahaman dengannya berbanding pesaingnya yang kira-kira sebaya ayah anda. Lagipun, dia sangat pandai bercakap.</p>",
			"img":"../img/story-0/4.svg",
			"more":1,
			"info":"<p>Tahukah anda apa itu Bias Pengesahan?</p><p>Ia apabila anda percaya pada satu-satu berita itu kerana berita itu menguatkan lagi kepercayaan atau nilai sedia ada yang anda pegang, tanpa mengetahui apakah maklumat itu sahih atau tidak. Contohnya, berita baik mengenai pemain bola sepak kegemaran anda atau berita buruk tentang vaksin sedangkan anda memang seorang antivaksin.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Jadi kenapa nak pertimbangkan calon lain?",
			"target0":"scenario-A_2",
		},
		{
			"id":"scenario-A_2",
			"text":"<p>Tiba hari mengundi, ketika sedang menuju ke pusat mengundi, anda mendapat teks pesanan.</p><p>Rakan sekelas anda memberitahu tentang satu khabar angin berkenaan calon lawan, tetapi kawan anda berpendapat calon itu menjadi mangsa fitnah.</p>",
			"img":"../img/story-0/5.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Apa seterusnya yang anda buat?",
			"target0":"scenario-A_3",
		},		
		{
			"id":"scenario-A_3",
			"text":"",
			"img1":"../img/story-0/6a-my.svg",
			"img2":"../img/story-0/6b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Abaikan sajalah!",
			"target0":"scenario-A1",
			"opt1":"Periksa fakta!",
			"target1":"scenario-B1-2",
		},
		{
			"id":"scenario-A1",
			"text":"<p>Ini tidak mengubah apa-apa bagi anda. Bahkan, anda semakin yakin bahawa calon pilihan anda itu adalah pilihan terbaik.</p>",
			"img":"../img/story-0/4.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Masa untuk mengundi!",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-A1_1",
			"text":"<p>Anda akhirnya mengundi Yasmin, calon TikTok anda.</p><p>Malangya, tidak lama kemudian, dia ingkar akan ikrar-ikrarnya. Lebih teruk, dia mula menyerang dan cuba mendiamkan para pengkritiknya, termasuk rakan-rakan anda!</p>",
			"img":"../img/story-0/7.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Tidak!",
			"target0":"scenario-A1_2",
		},		
		{
			"id":"scenario-A1_2",
			"text":"<p>Anda tertanya-tanya, apakah ada petanda awal terhadap semua ini? Mungkin jika anda membuat lebih banyak kajian, anda tidak akan mudah terpengaruh oleh propadanda dan janji-janji pilihan raya olehnya?</p>",
			"img":"../img/story-0/7.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"TAMAT",
			"target0":"scenario-end",
		},	
		{
			"id":"scenario-B",
			"text":"<p>Lagipun, dia tampak terlalu 'sempurna'. Tidak ada ruginya untuk mempertimbangkan segala pilihan yang ada.</p>",
			"img":"../img/story-0/5.svg",
			"more":1,
			"info":"<p>Jika anda terbaca atau terdengar sesuatu yang terlalu bagus sehingga susah untuk dipercayai, ada kalanya perkara itu memang tidak betul. Anda harus saring maklumat atau belajar lebih lagi mengenai sesuatu isu/tuduhan/calon/parti sebelum berpegang pada satu-satu pandangan.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Bagaimana mendapatkan maklumat?",
			"target0":"scenario-B_1",
		},	
		{
			"id":"scenario-B_1",
			"text":"",
			"img1":"../img/story-0/8a-my.svg",
			"img2":"../img/story-0/8b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Sudah tentulah internet dan media sosial!",
			"target0":"scenario-B1",
			"opt1":"Bercakap dengan ramai orang!",
			"target1":"scenario-B2",
		},		
		{
			"id":"scenario-B1",
			"text":"<p>Apa yang anda temukan?</p>",
			"img1":"../img/story-0/9a-my.svg",
			"img2":"../img/story-0/9b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Siapa sangka?",
			"target0":"scenario-B1-1",
			"opt1":"Kegiatan kotor!",
			"target1":"scenario-B1-2",
		},
		{
			"id":"scenario-B1-1",
			"text":"<p>Jega banyak mengemukakan idea yang baik. Manifestonya untuk menangani pengangguran belia agak meyakinkan. Mungkin dia tidaklah ketinggalan seperti yang anda sangkakan. Anda mula sedar, calon pertama tidaklah sesempurna mana, dan dia selama ini memberi gambaran salah tentang lawannya. </p>",
			"img":"../img/story-0/10.svg",
			"more":1,
			"info":"<p>Nampak? Dengan mengkaji dan mendengar sudut pandang orang lain, anda mampu untuk keluar dari 'ruang gema', mampu mengenal pasti bias yang mungkin mengaburi mata anda dari propaganda serta salah maklumat, dan telah mempengaruhi undi anda.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Masa untuk mengundi!",
			"target0":"scenario-B1-1_1",
		},
		{
			"id":"scenario-B1-1_1",
			"text":"<p>Anda akhirnya mengundi Jega. Tidak lama kemudian, anda terbaca bahawa Yasmin - calon TikTok pilihan anda sebelum ini - ingkar akan ikrar-ikrarnya. Lebih teruk, dia mula menyerang dan cuba mendiamkan para pengkritiknya, termasuk rakan-rakan anda!</p>",
			"img":"../img/story-0/11.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"TAMAT",
			"target0":"scenario-end",
		},	
		{
			"id":"scenario-B1-2",
			"text":"<p>Ketika memeriksa calon kedua, S. Jega, media sosial anda dibanjiri hantaran yang menyerangnya. Hantaran-hantaran itu membangkitkan perkara yang sama, meskipun dibuat oleh individu berbeza. Mereka menuduhnya pernah terlibat dengan rasuah, meskipun tiada sesiapa pun yang mengemukakan bukti.</p>",
			"img":"../img/story-0/12.svg",
			"more":1,
			"info":"<p>Oh, Laskar Siber</p><p>Laskar siber ialah orang yang dibayar untuk menyebarkan propaganda politik/ berita palsu di internet dan menyerang orang-orang tertentu secara khusus di dunia maya.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Hmm...",
			"target0":"scenario-B1-2_1",
		},
		{
			"id":"scenario-B1-2_1",
			"text":"<p>Jega menafikan tuduhan itu dan mendakwa menjadi mangsa kempen kotor parti pembangkang untuk menakut-nakutkan pengundi.</p>",
			"img":"../img/story-0/12.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Siapa yang anda percaya?",
			"target0":"scenario-B1-2_2",
		},
		{
			"id":"scenario-B1-2_2",
			"text":"",
			"img1":"../img/story-0/13a-my.svg",
			"img2":"../img/story-0/13b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Jega",
			"target0":"scenario-B1-2-1",
			"opt1":"Khabar angin",
			"target1":"scenario-B1-2-2",
		},
		{
			"id":"scenario-B1-2-1",
			"text":"<p>Anda tidak percaya bulat-bulat. Lagipun, tiada yang mengemukakan bukti atas tuduhan itu. Anda pun menyelidik, mencari sebarang maklumat berhubung insiden rasuah yang diperkatakan itu dan menemukan beberapa laporan berita lama.</p>",
			"img":"../img/story-0/14.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Tunggu sekejap!",
			"target0":"scenario-B1-2-1_1",
		},
		{
			"id":"scenario-B1-2-1_1",
			"text":"<p>Sebahagian laporan berita yang memburukkan Jega adalah dari portal yang anda tidak pernah dengar sebelum ini, atau mempunyai kaitan dengan parti ahli politik TikTok yang seorang lagi. Sementara itu, anda terjumpa laporan berita lain bahawa polis telah membersihkan nama Jega dari sebarang salah laku.</p>",
			"img":"../img/story-0/15.svg",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Masa untuk mengundi!",
			"target0":"scenario-B1-1_1",
		},
		{
			"id":"scenario-B1-2-2",
			"text":"<p>Anda mula sangsi terhadap kredibiliti calon ini. Kalau tuduhan itu tak betul, takkanlah ramai benar orang yang mengungkitnya berulang-ulang kali?</p>",
			"img":"../img/story-0/16.svg",
			"more":1,
			"info":"<p>Pernahkah anda dengar tentang Bias Mengikut Kumpulan atau Gelembung Sosial?</p><p>Bias mengikut kumpulan adalah apabila anda membentuk pendirian berdasarkan pandangan majoriti, atau tidak mahu berlawanan pendirian dengan mereka.</p><p>Gelembung sosial pula adalah apabila anda berinteraksi hanya dengan sekumpulan orang tertentu yang selalunya berkongsi pendirian serupa dengan anda. Ini membawa kepada 'ruang gema' apabila anda terdedah hanya kepada pandangan serupa, dan tidak terdedah kepada sudut pandang dan pendirian lain.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Majoriti takkan pernah salah, kan? ",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-B2",
			"text":"<p>Lebih elok lagi jika anda turut mendengar pandangan lain selain dari rakan-rakan sekepala. Rupa-rupanya, bukan semua orang percaya dengan calon kesukaan anda itu. Rakan-rakan bukan Melayu dalam kelas anda berasakan videonya terlalu melebih-lebih dan berbaur perkauman.</p>",
			"img":"../img/story-0/17.svg",
			"more":1,
			"info":"<p>Nampak? Dengan mengkaji dan mendengar sudut pandang orang lain, anda mampu untuk keluar dari 'ruang gema', mampu mengenal pasti bias yang mungkin mengaburi mata anda dari propaganda serta salah maklumat, dan telah mempengaruhi undi anda.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Menarik ...",
			"target0":"scenario-B2_1",
		},
		{
			"id":"scenario-B2_1",
			"text":"<p>Ada yang menyifatkan pesaingnya, Jega, mempunyai rekod perkhidmatan yang baik di kawasan. Mereka menunjukkan artikel berita di mana Yasmin memburuk-burukkan Jega dengan memainkan pandangan perkauman dan stereotaip.</p>",
			"img":"../img/story-0/18.svg",
			"more":1,
			"info":"<p>Jangan terperdaya dengan politik perkauman!</p><p>Politik perkauman atau ekstrem adalah apabila ahli politik menggunakan kaum atau isu-isu lain untuk memecahbelahkan pengundi atau orang awam.</p><p>Ia digunakan untuk melaga-lagakan satu kaum/kumpulan dengan yang lain demi mendapatkan keuntungan politik, atau untuk mengalihkan perhatian dari isu-isu lain.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Saya baru tahu",
			"target0":"scenario-B2_2",
		},
		{
			"id":"scenario-B2_2",
			"text":"<p>Katanya, mengundi Jega adalah tidak patriotik dan bermakna anda menentang seluruh kaum dan komuniti anda. </p>",
			"img":"../img/story-0/18.svg",
			"more":1,
			"info":"<p>Anda pernah dengar tentang Dikotomi Palsu/Perduaan Palsu?</p><p>Ia apabila seseorang itu diberikan hanya dua pilihan/sisi, sedangkan selalunya terdapat lebih banyak sisi/pilihan untuk dipilih.</p><p>Contohnya, mungkin ada orang memberitahu bahawa jika anda tidak bersetuju dengan sesuatu dasar kerajaan, maka anda menentang seluruh kerajaan, atau jika anda tidak bersetuju dengan seseorang calon wanita, maka anda antifeminis.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Sekarang macam mana? ",
			"target0":"scenario-B2_3",
		},
		{
			"id":"scenario-B2_3",
			"text":"",
			"img1":"../img/story-0/19a-my.svg",
			"img2":"../img/story-0/19b-my.svg",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Ikut kata hati",
			"target0":"scenario-B2-1",
			"opt1":"Cari lebih maklumat tentang calon lawan",
			"target1":"scenario-B1-1",
		},
		{
			"id":"scenario-B2-1",
			"text":"<p>Nampaknya, Yasmin ialah calon yang tepat. Lagipun, majoriti rakan-rakan rapat anda memang meminatinya. Nampaknya, dia memang calon pilihan. Majoriti tak pernah salah. Jika nanti dia rupa-rupanya seorang wakil rakyat yang culas, anda sentiasa berpeluang menyingkirkannya pada pilihan raya akan datang.</p>",
			"img":"../img/story-0/20.svg",
			"more":1,
			"info":"<p>Pernahkah anda dengar tentang Bias Mengikut Kumpulan atau Gelembung Sosial?</p><p>Bias mengikut kumpulan adalah apabila anda membentuk pendirian berdasarkan pandangan majoriti, atau tidak mahu berlawanan pendirian dengan mereka.</p><p>Gelembung sosial pula adalah apabila anda berinteraksi hanya dengan sekumpulan orang tertentu yang selalunya berkongsi pendirian serupa dengan anda. Ini membawa kepada 'ruang gema' apabila anda terdedah hanya kepada pandangan serupa, dan tidak terdedah kepada sudut pandang dan pendirian lain.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Masa untuk mengundi!",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-end",
			"text":"<p>Bila tiba hari pilihan raya, adalah menjadi hak setiap warganegara untuk mengundi. Namun ia tidak selalunya mudah dengan banyaknya propaganda, berita palsu dan helah lain untuk memperdaya pengundi. Lebih memburukkan keadaan, bias (yang kita semua miliki!) kadangkala boleh mengaburi mata kita dalam membuat pilihan yang tepat. Dengan mempelajari bagaimana mengenal pasti propaganda politik dan propaganda yang memecahbelahkan, salah maklumat dan bias, ia dapat membantu anda melunaskan tanggungjawab dan membuat pilihan termaklum yang pastinya mendatangkan manfaat buat anda dan negara.</p>",
			"endLinks":[
				"<a href='https://www.youtube.com/watch?v=Jqt7B857ooM' target='_blank'>The Vaccine for Fake News</a>",
				"<a href='https://sea.mashable.com/tech/20996/for-gen-z-tiktok-is-more-than-entertainment-its-a-search-engine' target='_blank'>For Gen Z, TikTok is more than entertainment. It's a search engine.</a>",
				"<a href='https://www.malaymail.com/news/malaysia/2021/01/14/report-malaysian-cybertrooper-teams-employ-full-time-staff-used-by-politici/1940305' target='_blank'>Report: Malaysian cybertrooper teams employ full-time staff, used by politicians and businesses alike</a>",
				"<a href='https://inoculation.science/inoculation-videos/' target='_blank'>Short videos that inoculate against misinformation online</a>",
			]
		}
	]	
];