var dataset = [
	[
		{
			"id":"scenario-0",
			"text":"<p>Kau merupakan seorang penjual sate pencen di dalam usia 70-an. Kau tinggal bersendirian bersama isteri. Prestasi perniagaan kau semakin teruk dan kau terpaksa terperuk di dalam rumah.</p>",
			"img":"../img/story-0/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Seterusnya",
			"target0":"scenario-0_1",
		},
		{
			"id":"scenario-0_1",
			"text":"<p>Isteri kau mengalami hidung berair dan seluruh badannya sakit. Kau khuatiri sekiranya Covid-19 tapi tak ada tanda-tanda serius kelihatan. Lagi pun, kau tidak percaya semua doktor dan kau enggan untuk mendapatkan nasihat pakar perubatan.</p>",
			"img":"../img/story-0/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Apa yang kau akan buat?",
			"target0":"scenario-0_2",
		},
		{
			"id":"scenario-0_2",
			"text":"",
			"img":"../img/story-0/1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Ape-ape pun berlaku, kau selidik terlebih dahulu gejala-gejala Covid-19",
			"target0":"scenario-A",
			"opt1":"Tak payah buat ape-ape. Alah, kita ni orang tua selalu sakit badan. Mestilah makan ubat Cap Ibu dan Anak pun dah cukup.",
			"target1":"scenario-B",
		},
		{
			"id":"scenario-A",
			"text":"<p>Tapi kat mana nak cari maklumat tu?</p>",
			"img":"../img/story-0/A.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Mana lagi? Tanya lah jiran sebelah!",
			"target0":"scenario-A1",
			"opt1":"Telefon Majlis Keselamatan Negara (MKN) <a href='https://www.mkn.gov.my/web/ms/talian-hotline-covid-19-agensi-kerajaan/' target='_blank'>hotline</a>. Bukan diorang selalu hantar SMS berlambak pasal Covid?",
			"target1":"scenario-A2",
		},
		{
			"id":"scenario-B",
			"text":"<p>Buat pertama kali, ubat Cap Ibu dan Anak tak berkesan. Isteri kau semakin tenat.</p>",
			"img":"../img/story-0/B.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Tiba-tiba kau teringat sesuatu",
			"target0":"scenario-B_1",
		},
		{
			"id":"scenario-B_1",
			"text":"<p>Kau teringat ada satu mesej WhatsApp daripada abang kau. Dia kongsi pasal air panas yang mujarab. Air tu dapat bunuh virus kalau kau minum. Tambah lagi, kalau kau makan ikan singgang pun boleh rawat penyakit Covid ni.</p>",
			"img":"../img/story-0/B.png",
			"more":1,
			"info":"<p>Di dalam satu wawancara TV pada bulan Mac 2020, Menteri Kesihatan Dr Adham Baba menasihati rakyat Malaysia supaya minum <a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'> air suam </a> untuk siram kebawah virus di dalam perut dimana asid pencernaan dapat membunuh virus tersebut. Ia adalah salah satu rawatan <a href='https://factcheck.afp.com/list-unproven-covid-19-treatments-debunked-health-experts' target='_blank'> yang tidak mempunyai bukti sah </a> untuk Covid-19 digelar maklumat palsu oleh ahli pakar perubatan <br> kau boleh semak sekiranya mesej dicipta oleh orang yang menghantar kepada kau dengan melihat <a href='https://faq.whatsapp.com/general/chats/about-forwarding-limits' target='_blank'> label <em>Forwarded</em> atau <em>Forwarded many times</em> </a> pada bahagian atas mesej tersebut. <em>Forwarded</em> bermaksud bahawa orang tersebut telah menerima mesej rantaian dari orang dan menyebarkan kepada kau.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Macam mana sekarang?",
			"target0":"scenario-B-b",
		},
		{
			"id":"scenario-B-b",
			"text":"",
			"img":"../img/story-0/B-b.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Teruskan dengan perubatan tradisional. Kalau abang yang hantar nasihat, mestilah betul, kan?",
			"target0":"scenario-B1",
			"opt1":"Tak kan lah semudah itu? Mungkin kau perlu periksa maklumat dulu?",
			"target1":"scenario-B2",
		},
		{
			"id":"scenario-A1",
			"text":"<p>Mana satu jiran yang kau nak bercakap pasal benda ni?</p>",
			"img":"../img/story-0/A1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Haa.. Mak Cik Maggie... Muka dia macam dia tau semua benda",
			"target0":"scenario-A1-1",
			"opt1":"Encik Syed kan kerja sebagai jururawat.... mestilah dia arif pasal benda-benda ni..",
			"target1":"scenario-A1-2",
		},
		{
			"id":"scenario-A1-2",
			"text":"<p>Dia tersentak ketakutan dan terus jauhkan diri dia dari kau seketika. Dia terus berkata: “Tak boleh ambil perkara macam ni dengan mudah, Pak Din! Kau kena call Kementerian Kesihatan secepat mungkin! Jangan jumpa doktor lagi, call diorang dulu!”</p>",
			"img":"../img/story-0/A1-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Kau nak dengar kata dia, ke?",
			"target0":"scenario-A1-2_1",
		},
		{
			"id":"scenario-A1-2_1",
			"text":"",
			"img":"../img/story-0/A1-2.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Ye lah. Encik Syed nampak macam baik dan bijak. Kau terus call Kementerian Kesihatan.",
			"target0":"scenario-A1-2-1",
			"opt1":"Tak payah lah. Terpulang kepada budi bicara kau untuk bertindak pantas atau tak dengan bawak isteri kau ke klinik yang terdekat.",
			"target1":"scenario-A1-2-2",
		},
		{
			"id":"scenario-A2",
			"text":"<p>Pengendali operator bagi nombor telifon untuk jabatan kesihatan yang terdekat. Isteri kau telah diuji dan dia disahkan dijangkiti dengan Covid-19.</p>",
			"img":"../img/story-0/A2.png",
			"more":1,
			"info":"<p>Jika kau mengalami gejala seperti demam, batuk atau sesak nafas, kau telah berada di dalam zon merah dan/atau telah dalam hubungan kontak kes positif Covid-19 di dalam tempoh 14 hari yang lalu, kau perlu berjumpa doktor di klinik kesihatan yang terdekat*. Walau bagaimanapun, kau perlu mengamalkan kaedah memakai penutup muka dan jarak sosial jauh ketika kau keluar untuk mendapatkan bantuan perubatan. Sekiranya kau tidak pasti, kau boleh hubungi <a href='http://covid-19.moh.gov.my/hotline' target='_blank'> hotline KKM </a>.<br>*Rujukan: <a href='http://covid-19.moh.gov.my/faqsop/faq-covid-19-kkm' target='_blank'>MOH</a></p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Kau pulak macam mana?",
			"target0":"scenario-A2_1",
		},
		{
			"id":"scenario-A2_1",
			"text":"<p>Kau juga diuji dan kau disahkan dijangkiti dengan Covid-19. Korang berdua akan dibawa ke hospital untuk dapatkan rawatan lanjut.</p>",
			"img":"../img/story-0/A2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-B1",
			"text":"<p>Keadaan isteri kau masih tidak sembuh. Kau berasa sangat risau. Pada masa yang sama, kau pun jatuh sakit.</p>",
			"img":"../img/story-0/B1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Alamak",
			"target0":"scenario-B1_1",
		},
		{
			"id":"scenario-B1_1",
			"text":"<p>Kau teringat dekat iklan <em>essential oil</em> yang dijamin mujarab dengan serangan virus. Iklan tu nampak macam professional dan mempunyai setem yang disahkan oleh Kementerian Kesihatan.</p>",
			"img":"../img/story-0/B1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Hmm...",
			"target0":"scenario-B1_2",
		},
		{
			"id":"scenario-B1_2",
			"text":"<p>Nak cuba ke minyak <em>essential oil</em> ni?</p>",
			"img":"../img/story-0/B1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Cepat-cepat kau order satu botol melalui WhatsApp",
			"target0":"scenario-B1-1",
			"opt1":"Eh, jangan. Kau terus call 999.",
			"target1":"scenario-B1-2",
		},
		{
			"id":"scenario-B1-2",
			"text":"<p>Pengendali operator bagi nombor telifon untuk jabatan kesihatan yang terdekat. Isteri anda telah diuji dan dia disahkan dijangkiti dengan Covid-19.</p>",
			"img":"../img/story-0/A2.png",
			"more":1,
			"info":"<p>Jika kau mengalami gejala seperti demam, batuk atau sesak nafas, kau telah berada di dalam zon merah dan/atau telah dalam hubungan kontak kes positif Covid-19 di dalam tempoh 14 hari yang lalu, kau perlu berjumpa doktor di klinik kesihatan yang terdekat*. Walau bagaimanapun, kau perlu mengamalkan kaedah memakai penutup muka dan jarak sosial jauh ketika kau keluar untuk mendapatkan bantuan perubatan. Sekiranya kau tidak pasti, kau boleh hubungi <a href='http://covid-19.moh.gov.my/hotline' target='_blank'> hotline KKM </a>.<br>*Rujukan: <a href='http://covid-19.moh.gov.my/faqsop/faq-covid-19-kkm' target='_blank'>MOH</a></p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-B1-2_1",
		},
		{
			"id":"scenario-B1-2_1",
			"text":"<p>Kau juga diuji dan kau disahkan dijangkiti dengan Covid-19. Korang berdua dibawa ke hospital untuk dapatkan rawatan lanjut.</p>",
			"img":"../img/story-0/A2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-B2",
			"text":"<p>Kau sedar yang kebanyakkan maklumat penawar untuk Covid-19 adalah tahyul, pseudosains yang telah dibuktikan palsu atau tidak disokong oleh bukti perubatan.</p>",
			"img":"../img/story-0/B-b.png",
			"more":1,
			"info":"<p>Wabak Covid-19 telah mendorong ke gelombang <a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'> ubat penawar palsu </a> dikongsi dalam alam maya. Penjual-penjual yang tidak bertanggungjawab telah megambil kesempatan dengan menyebarkan perasaan takut dan bimbang rakyat demi menjual produk mereka untuk melawan virus. <a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'> jamu </a> dan <a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'> rantai leher anti-virus </a>. Juga <a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'> syarikat Malaysia </a> yang menjual penutup muka di alam maya dengan harga inflasi dengan menggunakan iklan serta halaman Facebook yang mengelirukan.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Seterusnya",
			"target0":"scenario-B2_1",
		},
		{
			"id":"scenario-B2_1",
			"text":"<p>Kau buat keputusan yang baik dengan mendapatkan nasihat pakar dan hubungi pihak Majlis Keselamatan Negara <a href='https://www.mkn.gov.my/web/ms/talian-hotline-covid-19-agensi-kerajaan/' target='_blank'>hotline</a>. Bukan diorang selalu hantar SMS berlambak pasal Covid?</p>",
			"img":"../img/story-0/B-b.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Call hotline",
			"target0":"scenario-A1-2-1",
		},
		{
			"id":"scenario-A1-1",
			"text":"<p>Dia berkata, “Pak Din... Tak payah nak risau sangat. Selsema sahaja. Anak saya pun hidap penyakit yang sama. Kita tak boleh percaya sangat dengan nasihat doktor ni, mereka ni nak duit kita sahaja”</p>",
			"img":"../img/story-0/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Kau nak dengar kata dia?",
			"target0":"scenario-A1-1_1",
		},
		{
			"id":"scenario-A1-1_1",
			"text":"",
			"img":"../img/story-0/A1-1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Jangan. Kau dah buat keputusan untuk periksa dengan jiran yang lain, Encik Syed.",
			"target0":"scenario-A1-2",
			"opt1":"Ye lah. Mak Cik Maggie nampak macam baik dan bijak.",
			"target1":"scenario-B1",
		},
		{
			"id":"scenario-A1-2-1",
			"text":"<p>Pengendali operator memberikan nombor telifon untuk jabatan kesihatan yang terdekat. Isteri kau telah diuji dan dia disahkan dijangkiti dengan Covid-19.</p>",
			"img":"../img/story-0/B2.png",
			"more":1,
			"info":"<p>Jika kau mengalami gejala seperti demam, batuk atau sesak nafas, kau telah berada di dalam zon merah dan/atau telah dalam hubungan kontak kes positif Covid-19 di dalam tempoh 14 hari yang lalu, kau perlu berjumpa doktor di klinik kesihatan yang terdekat*. Walau bagaimanapun, kau perlu mengamalkan kaedah memakai penutup muka dan jarak sosial jauh ketika kau keluar untuk mendapatkan bantuan perubatan. Sekiranya kau tidak pasti, kau boleh hubungi <a href='http://covid-19.moh.gov.my/hotline' target='_blank'> hotline KKM </a>.<br>*Rujukan: <a href='http://covid-19.moh.gov.my/faqsop/faq-covid-19-kkm' target='_blank'>MOH</a></p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-2-1_1",
		},
		{
			"id":"scenario-A1-2-1_1",
			"text":"<p>Kau juga diuji dan disahkan dijangkiti dengan Covid-19. Korang berdua dibawa ke hospital untuk dapatkan rawatan lanjut.</p>",
			"img":"../img/story-0/B2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-2-2",
			"text":"<p>Sehari selepas itu, kau dapat keputusan ujian, dia jugak positif untuk Covid. Sekarang, kau pun kena dapat kan ujian yang sama.</p>",
			"img":"../img/story-0/A1-2-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-2-2_1",
		},
		{
			"id":"scenario-A1-2-2_1",
			"text":"<p>Lebih teruk lagi, seluruh klinik harus ditutup untuk urusan sanitasi dan pihak berkuasa bergegas mengesan kesemua kakitangan dan pesakit yang berada pada lokasi yang sama supaya mereka jugak akan disaringkan. </p>",
			"img":"../img/story-0/A1-2-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-2-2_2",
		},
		{
			"id":"scenario-A1-2-2_2",
			"text":"<p>Keputusan kau yang terburu-buru mempunyai potensi untuk menular jangkitan Covid kepada orang lain.</p>",
			"img":"../img/story-0/A1-2-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-B1-1",
			"text":"<p>Perkhidmatan diberikan pantas dan cekap, dan botol kau tiba di depan pintu rumah keesokkan harinya. Kau dan isteri terus mengambil satu dos 'ubat' tersebut.</p>",
			"img":"../img/story-0/B1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Berkesan, ke?",
			"target0":"scenario-B1-1_1",
		},
		{
			"id":"scenario-B1-1_1",
			"text":"<p>Suatu perkara aneh yang telah berlaku. Kau mula berasa sakit perut dan korang berdua mula muntah. Kau terus hubungi 999 dan secara tiba-tiba, kau jatuh pengsan. Bunyi terakhir yang kau dengar merupakan suara jeritan isteri kau yang mengadu kesakitan.</p>",
			"img":"../img/story-0/B1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-B1-1-1",
		},
		{
			"id":"scenario-B1-1-1",
			"text":"<p>Apabila kau terjaga dari tidur, kau berada di dalam hospital. Kau telah didapati positif untuk Covid dan kau berada di dalam ICU. Ubat yang kau dah telan merupakan racun.</p>",
			"img":"../img/story-0/B1-2.png",
			"more":1,
			"info":"<p>Setakat ini, tiada penawar khusus untuk Covid-19. Rawatan sepenuhnya diberikan kepada pesakit yang hidapi gejal-gejala yang berkaitan. Walau bagaimanapun, Malaysia sedang berusaha untuk mendapatkan vaksin supaya kita boleh bina ketahanan badan terhadap virus. <a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>  Penipu-penipu </a> membanjiri di media sisial dengan informasi mengenai penawar palsu serta ujian yang berkaitan.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Isteri kau macam mana pulak?",
			"target0":"scenario-B1-1-1_1",
		},
		{
			"id":"scenario-B1-1-1_1",
			"text":"<p>Dengan perasaan pilu, mereka mengabarkan berita sedih yang isteri kau telah meninggal dunia akibat keracunan. Kesemua dakwaan yang dipasarkan melalui iklan <em>essential oil</em> tu sebenarnya palsu.</p>",
			"img":"../img/story-0/B1-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-end",
			"text":"<p>Semasa krisis global seperti pandemik Covid-19, maklumat yang tepat boleh membantu menyelamatkan nyawa. Namun, terdapat beberapa orang yang sengaja membuat tuntutan palsu untuk kepentingan peribadi. </p><p> Oleh itu, di dalam era maklumat yang menyaratkan, mencari serta mengkritik nilai maklumat di alam maya merupakan satu set kemahiran yang diperlukan. Kau tak boleh percaya secara bulat dan berkongsi apa-apa maklumat yang kau tak pasti 100% faktanya, tidak kira lah dari mana kau dapat maklumat tersebut dan bagaimana ia boleh dipercayai. Seperti di dalam cerita ini, akibat apabila mempercayai maklumat palsu boleh meletakkan diri kau dan orang lain dalam keadaan yang berisiko tinggi.</p><p>Kau boleh terus main dua karakter yang lain untuk mengetahui lebih lanjut mengenai maklumat palsu dari perspektif mereka.</p>",
			"endLinks":[
				"<a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>Coronavirus scammers are flooding social media with fake cures and tests</a>",
				"<a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'>Iran: Over 700 dead after drinking alcohol to cure coronavirus</a>",
				"<a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'>Arizona man dies after attempting to take Trump coronavirus 'cure'</a>",
				"<a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'>Health Minister's 'warm water method' to kill coronavirus questioned</a>",
				"<a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'>Baseless Covid-19 cure-alls rampant in Malaysia despite authorities' warning</a>",
				"<a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'>Indonesia's false coronavirus 'cures' draw concern from scientists</a>",
				"<a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'>‘Complete scam’: Anti-virus ‘Shut Out’ necklaces sold across Hong Kong despite bans around Asia</a>",
				"<a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'>Facebook Banned Mask Ads. They're Still Running.</a>",
			]
		}
	],
	[
		{
			"id":"scenario-0",
			"text":"<p>Penjaja gerai kegemaran kau dekat dengan rumah. Mi buatan mak cik ini terkenal dan biasanya, kau akan pergi awal untuk elak beratur panjang.</p>",
			"img":"../img/story-1/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Jadi, apa yang berubah?",
			"target0":"scenario-0_1",
		},
		{
			"id":"scenario-0_1",
			"text":"<p>Minggu lepas, gerai mi tersebut telah ditutup dan mak cik tu tidak kelihatan sejak beberapa hari. Kau terdengar dari penjual-penjual yang lain cakap mak cik ni kena jangkit dengan Covid-19.</p>",
			"img":"../img/story-1/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Seterusnya",
			"target0":"scenario-0_2",
		},
		{
			"id":"scenario-0_2",
			"text":"<p>Kau berasa risau. Keluarga kau kerap membeli makanan di medan selera tu, terutamanya gerai tersebut. Kau nak pastikan keluarga kau selamat, terutamanya apabila kes Covid di kawasan kau meningkat.</p>",
			"img":"../img/story-1/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Apa yang kau akan buat?",
			"target0":"scenario-0_3",
		},
		{
			"id":"scenario-0_3",
			"text":"",
			"img":"../img/story-1/1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Cepat-cepat kau bagi amaran kepada ahli keluarga dan sahabat handai. Selamat kan diri sekarang daripada menyesal kemudian hari! Lagipun, kalau tak betul, tak betul lah.",
			"target0":"scenario-A",
			"opt1":"Lebih baik kau semak terlebih dahulu sekiranya tuntutan tersebut adalah benar. Tak perlu kelam kabut.",
			"target1":"scenario-B",
		},
		{
			"id":"scenario-A",
			"text":"<p>Kau mula mereka cipta amaran di media sosial untuk menyebarkan. Contoh tweet ”Gais, lebih baik berhati-hati. Dengar cerita, gerai mi udang mak cik ni kena jangkit dengan Covid! Dekat siot dengan rumah! #stayhome #covid19 #staysafe”</p>",
			"img":"../img/story-1/A.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Apa yang kau akan buat?",
			"target0":"scenario-A_1",
		},
		{
			"id":"scenario-A_1",
			"text":"",
			"img":"../img/story-1/A.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Tekan hantar. Lebih baik hantar secepat mungkin. Kau berasa seronok sebab kau dah menjalankan tanggungjawab kau untuk menyelamatkan masyarakat sejagat.",
			"target0":"scenario-A1",
			"opt1":"Kau teragak-agak. Macam mana kalau mak cik ni tak dijangkit dengan Covid? Kesian lah dia.",
			"target1":"scenario-A2",
		},
		{
			"id":"scenario-B",
			"text":"<p>Habis tu, macam nak semak?</p>",
			"img":"../img/story-1/A.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Tanya penjaja-penjaja yang buat cerita ni. Dari siapa diorang dengar?",
			"target0":"scenario-B1",
			"opt1":"Cari laporan di dalam akhbar. Mesti ada orang yang sedang mengesan semua lokasi yang terjejas meskipun Kementerian Kesihatan tak nak kongsi maklumat yang kau perlukan.",
			"target1":"scenario-B2",
		},
		{
			"id":"scenario-A1",
			"text":"<p>Member-member kau dan beberapa pengguna Internet mula minta kau kongsi dengan diorang gambar mak cik dan gerai dia. Kau nak kongsi ke tak?</p>",
			"img":"../img/story-1/A1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Bagi je lah! Lagipun, apa-apa yang dapat membantu orang ramai berasa selamat. Kau bagi diroang pin lokasi Google pun jadilah.",
			"target0":"scenario-A1-1",
			"opt1":"Eh, jangan lah! Itu maklumat peribadi. Gambar tu boleh disalah gunakan kalau jatuh di tangan yang salah.",
			"target1":"scenario-A1-2",
		},
		{
			"id":"scenario-A2",
			"text":"",
			"img":"../img/story-1/B.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Kau dah membuat keputusan untuk tak menghantar mesej tersebut. Sebaliknya, kau hanya mampu mengunggu dan lihat sekiranya mak cik tu akan kembali atau jika pegawai kesihatan tiba untuk membersihkan kawasan tu.",
			"target0":"scenario-B2-1",
			"opt1":"Kau dah membuat keputusan untuk menghantar mesej tersebut tapi nama mak cik tu dan gerai dia dikeluarkan.",
			"target1":"scenario-A2-2",
		},
		{
			"id":"scenario-A2-2",
			"text":"<p>Keesokkan harinya, mesej yang kau hantar dah jadi viral. Kau berasa puas hati. Kau percaya bahawa kau dah dah bantu rakyat untuk kekal rasa selamat dan sedia maklum. Tiba-tiba, kau terserempak mak cik tu dah balik ke gerainya.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Kau cakap dengan dia",
			"target0":"scenario-A2-2_1",
		},
		{
			"id":"scenario-A2-2_1",
			"text":"<p>Rupa-rupanya, dia tak pernah jatuh sakit pun tapi tapi dia pergi melawat anak perempuannya. Dia bagitau kau pasal prestasi perniagaaannya terjejas teruk begitu juga penjaja-penjaja lain disebabkan penularan berita palsu yang mengatakan beberapa penjaja di kawasan ni dijangkiti dengan Covid-19.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":1,
			"info":"<p>Pada bulan Februari 2020, penjaja di <a href='https://www.sinchew.com.my/content/content_2214185.html' target='_blank'> di pasar pagi di Batu Pahat </a> kehilangan 80% daripada perniagaan mereka selepas berita palsu ditular di Facebook dan mendakwa bahawa beberapa penjaja di pasar pagi tersebut pulang dari China. Walaupun mesej palsu itu telah dipadamkan dan penjelasan situasi sebenar telah disebarkan, namun, berita palsu itu terus ditular secara meluas. Satu kajian selidik oleh Massachusetts Institute of Technology telah dapati bahawa berita palsu bergerak <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> daripada berita sebenar.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Alamak!",
			"target0":"scenario-A2-2_2",
		},
		{
			"id":"scenario-A2-2_2",
			"text":"<p>Kau nak mengaku kat mak cik ni pasal perbuatan kau dan kau cuba untuk memperbaiki kesilapan kau?</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Ye lah! Dia layak untuk tahu cerita sebenar!",
			"target0":"scenario-A1-2-1-1",
			"opt1":"Kau berasa berat hati tapi kau rasa terlalu malu untuk bagitau dia yang kau yang sebarkan berita palsu tu.",
			"target1":"scenario-A1-1-1-1_1",
		},
		{
			"id":"scenario-B1",
			"text":"<p>Kau tak dapat kesan siapa yang mempunya pengalaman pertama untuk sahkan khabar angin tersebut. Selama ni, berita palsu tu dikhabarkan yang virus sedang merebak dan kes baru ditemui setiap hari, berdekatan dengan rumah kau atau kawasan kediaman kolej kau.</p>",
			"img":"../img/story-1/B1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Apa lagi yang kau akan buat?",
			"target0":"scenario-B1_1",
		},
		{
			"id":"scenario-B1_1",
			"text":"",
			"img":"../img/story-1/B1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Kau dah buat keputusan untuk hantar amaran di media sosial dan aplikasi mesej.",
			"target0":"scenario-A",
			"opt1":"Cari laporan di dalam akhbar harian. Seseorang sepatutnya mengesan kesemua lokasi yang terjejas, walaupun Kementerian Kesihatan tidak berkongsi maklumat tersebut.",
			"target1":"scenario-B2",
		},
		{
			"id":"scenario-B2",
			"text":"<p>Kau tak jumpa gerai mak cik ni dilaporkan atau disenaraikan dimana-mana laporan media masa.</p>",
			"img":"../img/story-1/B2.png",
			"more":1,
			"info":"<p>Banyak lokasi terjejas oleh kes Covid-19 telah dilaporkan oleh media, contohnya <a href='https://newslab.malaysiakini.com/covid-19/en' target='_blank'> pengesan Covid-19 </a>.  Satu carian Google dapat membantu anda untuk mengenal pasti lokasi tempat. Walau bagaimanapun, kau harus pastikan maklumat tersebut disahkan oleh pihak media yang bereputasi dan/atau sumber yang dipercayai.</p>",
			"optNum":1,
			"optImg":1,
			"opt0":"Kau dah buat keputusan bahawa ia tidak selamat untuk berkongsi maklumat yang mungkin palsu.",
			"target0":"scenario-B2-1",
			"opt1":"Untuk berada di pihak yang benar, kau dah buat keputusan untuk hantar mesej tetapi tidak menyebut nama gerai mak cik itu.",
			"target1":"scenario-A2-2",
		},
		{
			"id":"scenario-B2-1",
			"text":"<p>Keesokkan harinya, kau terserempak mak cik di belakang gerainya. Sebenarnya, mak cik ni tak pernah jatuh sakit tetapi dia hanya pergi melawat anak perempuannya. Kau berasa lega yang kau tak sebar berita palsu.</p>",
			"img":"../img/story-1/B2-1.png",
			"more":1,
			"info":"<p>Pada bulan Februari 2020, penjaja di <a href='https://www.sinchew.com.my/content/content_2214185.html' target='_blank'> di pasar pagi di Batu Pahat </a> kehilangan 80% daripada perniagaan mereka selepas berita palsu ditular di Facebook dan mendakwa bahawa beberapa penjaja di pasar pagi tersebut pulang dari China. Walaupun mesej palsu itu telah dipadamkan dan penjelasan situasi sebenar telah disebarkan, namun, berita palsu itu terus ditular secara meluas. Satu kajian selidik oleh Massachusetts Institute of Technology telah dapati bahawa berita palsu bergerak <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> daripada berita sebenar.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-1",
			"text":"<p>Mesej yang kau hantar telah menjadi viral. Kau berasa gembira. Kau percaya bahawa kau telah membantu rakyat kekal selamat dan maklum. Beberapa hari selepas itu, kau terserempak mak cik tu! Muka dia nampak marah dan dia sedang mengemaskan barang-barangnya.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Kau cakap dengan dia",
			"target0":"scenario-A1-1_1",
		},
		{
			"id":"scenario-A1-1_1",
			"text":"<p>Rupa-rupanya, mak cik ni tak pernah sakit tetapi dia baru sahaja pergi melawat anak perempuannya. Dia bagitau kau yang ada orang buat cerita jahat pasal dia dijangkiti Covid, termasuk kongsi gambar sebenar dia.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Alamak!",
			"target0":"scenario-A1-1_2",
		},
		{
			"id":"scenario-A1-1_2",
			"text":"<p>Lebih teruk lagi, dia diganggu oleh orang yang hantar mesej kesat dan kongsi gambar beliau, mengganggap beliau menularkan Covid. Mak cik tu bagitau dekat anak perempuannya akan lapor kat pihak polis.</p>",
			"img":"../img/story-1/A1-1b.png",
			"more":1,
			"info":"<p>Pada bulan Februari 2020, penjaja di <a href='https://www.sinchew.com.my/content/content_2214185.html' target='_blank'> di pasar pagi di Batu Pahat </a> kehilangan 80% daripada perniagaan mereka selepas berita palsu ditular di Facebook dan mendakwa bahawa beberapa penjaja di pasar pagi tersebut pulang dari China. Walaupun mesej palsu itu telah dipadamkan dan penjelasan situasi sebenar telah disebarkan, namun, berita palsu itu terus ditular secara meluas. Satu kajian selidik oleh Massachusetts Institute of Technology telah dapati bahawa berita palsu bergerak <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> daripada berita sebenar.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Macam mana sekarang?",
			"target0":"scenario-A1-1_3",
		},
		{
			"id":"scenario-A1-1_3",
			"text":"<p>Kau nak mengaku kat mak cik pasal perbuatan kau dan cuba untuk memperbaiki kesilapan kau?</p>",
			"img":"../img/story-1/A1-1b.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Mestilah lah! Dia layak untuk tahu cerita sebenar dan kau tak nak polis cari kau.",
			"target0":"scenario-A1-1-1",
			"opt1":"Jangan! Malu lah! Kau dah bagitau semua orang yang dia positif Covid-19.",
			"target1":"scenario-A1-1-2",
		},
		{
			"id":"scenario-A1-2",
			"text":"<p>Mesej yang kau hantar dah jadi viral. Kau berasa gembira. Kau percaya bahawa kau telah bantu rakyat kekal rasa selamat dan sedia maklum. Beberapa hari selepas itu, kau terserempak mak cik itu! Dia nampak marah dan sedang mengemaskan barang-barangnya.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Bercakap dengan dia",
			"target0":"scenario-A1-2_1",
		},
		{
			"id":"scenario-A1-2_1",
			"text":"<p>Rupa-rupanya, mak cik tidak pernah sakit tetapi dia baru sahaja pergi melawat anak perempuannya. Dia bagitau kau yang ada orang buat cerita jahat pasal dia dijangkiti Covid, termasuk kongsi gambar sebenar dia.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Alamak!",
			"target0":"scenario-A1-2_2",
		},
		{
			"id":"scenario-A1-2_2",
			"text":"<p>Sekarang, dia dah kehilangan 90% daripada peniagaannya dan dia kena tutup peniagaan dia yang dah lama beroperasi lebih 40 tahun.</p>",
			"img":"../img/story-1/A1-1.png",
			"more":1,
			"info":"<p>Pada bulan Februari 2020, penjaja di <a href='https://www.sinchew.com.my/content/content_2214185.html' target='_blank'> di pasar pagi di Batu Pahat </a> kehilangan 80% daripada perniagaan mereka selepas berita palsu ditular di Facebook dan mendakwa bahawa beberapa penjaja di pasar pagi tersebut pulang dari China. Walaupun mesej palsu itu telah dipadamkan dan penjelasan situasi sebenar telah disebarkan, namun, berita palsu itu terus ditular secara meluas. Satu kajian selidik oleh Massachusetts Institute of Technology telah dapati bahawa berita palsu bergerak <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> daripada berita sebenar.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Macam mana ni?",
			"target0":"scenario-A1-2_3",
		},
		{
			"id":"scenario-A1-2_3",
			"text":"<p>Kau nak mengaku atau tak kepada mak cik mengenai perbuatan kau dan cuba untuk memperbaiki kesilapan kau?</p>",
			"img":"../img/story-1/A1-1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Mesti lah! Dia layak untuk mengetahui cerita sebenar.",
			"target0":"scenario-A1-2-1-1",
			"opt1":"Tak nak lah! Malu lah... kau dah bagitau semua orang yang dia positif Covid-19.",
			"target1":"scenario-A1-1-1-1_1",
		},
		{
			"id":"scenario-A1-1-2",
			"text":"<p>Beberapa hari kemudian, polis datang mengetuk pintu rumah kau. Polis telah mengesan punca berita palsu datang daripada kau.</p>",
			"img":"../img/story-1/A1-1-2.png",
			"more":1,
			"info":"<p>Ratusan orang disyaki menyebar berita palsu telah disiasat pada tahun 2020 termasuk <a href='https://www.bernama.com/en/general/news_covid-19.php?id=1869002' target='_blank'> seorang perempuan </a> yang membuat dakwaan palsu mengenai sebuah pasaraya ditutup akibat Covid-19. Sehingga Oct 8, 2020, pihak berkuasa telah membuka hampir <a href='https://bernama.com/en/general/news_covid-19.php?id=1887864' target='_blank'> 300 siasatan </a> berkaitan dengan kesalahan tersebut dan 35 individu telah didakwa. Sebahagian besar daripada mereka disiasat di bawah Seksyen 233 Akta Komunikasi dan Multimedia 1998 dan Seksyen 505 (b) Kanun Keseksaan. Kerajaan memberi amaran bahawa walaupaun <a href='https://www.thestartv.com/v/deleted-false-news-on-mco-will-still-be-investigated-says-ismail-sabri' target='_blank'> maklumat palsu yang telah dipadam </a> masih boleh disiasat.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Habislah",
			"target0":"scenario-A1-1-2_1",
		},
		{
			"id":"scenario-A1-1-2_1",
			"text":"<p>Kau kena tangkap untuk dalam siasatan. Kau tak sedar akibat menular berita palsu akan menyebabkan kau didakwa.</p>",
			"img":"../img/story-1/A1-1-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-1-1",
			"text":"<p>Kau minta maaf kat dia dan memadam status media sosial kau. Dia terima kemaafan kau dan buat keputusan untuk tak laporkan kat polis. Kau juga dah hantar mesej baru untuk bagi penjelasan pasal situasi sebenar dan memohon maaf atas perbuatan menyebarkan berita palsu.</p>",
			"img":"../img/story-1/A1-1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-1-1_1",
		},
		{
			"id":"scenario-A1-2-1-1",
			"text":"<p>Kau minta maaf kat dia dan memadam status media sosial kau. Dia terima kemaafan kau dan buat keputusan untuk tak laporkan kat polis. Kau juga dah hantar mesej baru untuk bagi penjelasan pasal situasi sebenar dan memohon maaf atas perbuatan menyebarkan berita palsu.</p>",
			"img":"../img/story-1/A1-1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-1-1_1",
		},
		{
			"id":"scenario-A1-1-1_1",
			"text":"<p>Fuh! Kau berasa lega yang kau dah betulkan kesilapan yang tidak disengajakan. Mak cik bagitau yang dia akan cuba meneruskan perniagaannya pada hari berikutnya.</p>",
			"img":"../img/story-1/A1-1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Krisis dah selesai!",
			"target0":"scenario-A1-1-1-1",
		},
		{
			"id":"scenario-A1-1-1-1",
			"text":"<p>Walau bagaimanapun, ia seolah-olah tidak berkesan. Mesej yang palsu terus menular tetapi penjelasan kau tidak dapat banyak perhatian di media sosial.</p>",
			"img":"../img/story-1/A1-2.png",
			"more":1,
			"info":"<p>Satu kajian selidik oleh Massachusetts Institute of Technology telah dapati bahawa berita palsu bergerak <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> dan sampai ke lebih ramai orang berbanding berita sebenar. Walaupun, kau mempunyai niat yang baik untuk menyebarkan suatu maklumat yang boleh disyaki palsu, ia amat sukar untuk memperbetulkan kesalahan yang telah dilakukan. Jadi, berhenti seketika dan berfikir sebelum menghantar apa-apa maklumat.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Sekarang, kau berasa menyesal sebab kau tidak bertindak begitu pantas tapi tak ada apa-apa yang kau mampu lakukan sekarang.",
			"target0":"scenario-A1-1-1-1_1",
		},
		{
			"id":"scenario-A1-1-1-1_1",
			"text":"<p>Beberapa hari kemudian, polis datang mengetuk pintu rumah kau. Salah satu penjaja yang perniagaannya terjejas di kawasan sama telah membuat laporan polis.</p>",
			"img":"../img/story-1/A1-1-2.png",
			"more":1,
			"info":"<p>Ratusan orang disyaki menyebar berita palsu telah disiasat pada tahun 2020 termasuk <a href='https://www.bernama.com/en/general/news_covid-19.php?id=1869002' target='_blank'> seorang perempuan </a> yang membuat dakwaan palsu mengenai sebuah pasaraya ditutup akibat Covid-19. Sehingga Oct 8, 2020, pihak berkuasa telah membuka hampir <a href='https://bernama.com/en/general/news_covid-19.php?id=1887864' target='_blank'> 300 siasatan </a> berkaitan dengan kesalahan tersebut dan 35 individu telah didakwa. Sebahagian besar daripada mereka disiasat di bawah Seksyen 233 Akta Komunikasi dan Multimedia 1998 dan Seksyen 505 (b) Kanun Keseksaan. Kerajaan memberi amaran bahawa walaupaun <a href='https://www.thestartv.com/v/deleted-false-news-on-mco-will-still-be-investigated-says-ismail-sabri' target='_blank'> maklumat palsu yang telah dipadam </a> masih boleh disiasat.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Mampus lah...",
			"target0":"scenario-A1-1-2_1",
		},
		{
			"id":"scenario-end",
			"text":"<p>Jangan sekali-kali berkongsi sebarang maklumat yang kau tak pasti 100% faktanya, tak kira lah dari mana kau dapat maklumat tersebut. Walaupun ia nampak seakan-akan benar sekalipun. Berkongsi maklumat palsu yang mengelirukan bukan sahaja membawa risiko, malah mampu meletakkan seseorang dalam keadaan bahaya kepada kehidupan seseorang itu. Niat baik kau mungkin membawa akibat yang buruk pada hidup orang lain. Jadi, sentiasa lah semak terlebih dahulu maklumat yang kau terima sebelum berkongsi. Terlalu banyak jumlah berita yang mengandungi maklumat palsu yang mengelirukan direka cipta dan ditular oleh orang yang mempunya motif tersembunyi.</p><p>Main lagi dua watak yang lain untuk mempelajari secara lanjut mengenai maklumat palsu dari perspektif mereka.</p>",
			"endLinks":[
				"<a href='https://www.sinchew.com.my/content/content_2214185.html' target='_blank'>染疫假消息影响生意‧峇株花园小贩中心冷清清 (Fake Covid-19 news affects business at Taman Batu Pahat hawker center)</a>",
				"<a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'>Study: On Twitter, false news travels faster than true stories</a>",
				"<a href='https://www.bernama.com/en/general/news_covid-19.php?id=1869002' target='_blank'>COVID-19: Woman nabbed for spreading fake news on supermarket closure</a>",
				"<a href='https://coconuts.co/kl/news/malaysia-man-criticized-after-naming-black-man-number-one-suspect-in-us-shooting/' target='_blank'>Malaysia man criticized after naming Black man ‘number one suspect’ in US shooting</a>",
			]
		}
	],
	[
		{
			"id":"scenario-0",
			"text":"<p>Kau merupakan seorang jurutera permainan tetapi kerja tidak membawa hasil yang lumayan. Untuk tambah lagi duit, kau tertarik dengan satu iklan dari alam maya sebagai <em>content creator</em>. Kau terima panggilan telefon & ditawarkan satu pekerjaan untuk kau.</p>",
			"img":"../img/story-2/1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Kerja apa tu?",
			"target0":"scenario-0_1",
		},
		{
			"id":"scenario-0_1",
			"text":"<p>Dia kata kau boleh mereka cipta apa sahaja kandungan yang kau inginkan dan kau akan mendapat komisen berdasarkan jumlah klik yang diterima. Dia menjanjikan komisen bulanan lima angka jika kandungan kau terbit viral.</p>",
			"img":"../img/story-2/1.png",
			"more":1,
			"info":"<p><em>Content farm/mills</em> merujuk kepada laman web yang menerbitkan kandungan berkualiti rendah dalam jumlah yang besar. Ia selalunya menggunakan tajuk yang sensasi untuk memancing klik dan <em>views</em> dengan tujuan menjana pendapatan iklan atau mempengaruhi pendapat umum. Disebabkan tujuannya adalah untuk menarik perhatian, kandungannya selalu mengandungi maklumat palsu dan mengelirukan.</p><p>Bagaimana mengenalpasti <em>content mills</em>? Selalunya mereka tidak menyatakan nama pengarang atau sumber maklumat. Mereka bergantung kepada <em>headline</em> yang sensasi untuk menarik perhatian dan tidak memberikan maklumat penerbit.</p><p> Menurut satu siasatan, <a href=’https://www.twreporter.org/a/information-warfare-business-disinformation-fake-news-behind-line-groups-english’ target=’_blank’>terdapat satu rangkaian besar <em>content farms</em></a> beroperasi di Malaysia yang mensasarkan komuniti berbahasa Cina di Asia.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Fuyoh!",
			"target0":"scenario-0_2",
		},
		{
			"id":"scenario-0_2",
			"text":"<p>Dah ada idea! Kau tahu pada ketika dalam zaman Covid-19, perasaan takut akan mendorong orang ramai untuk percaya apa-apa sahaja. Apa yang akan kau buat?</p>",
			"img":"../img/story-2/1_1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Apa yang akan kau buat?",
			"target0":"scenario-0_3",
		},
		{
			"id":"scenario-0_3",
			"text":"",
			"img":"../img/story-2/1_1.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Apa lagi... Ambik je lah tawaran tu... Ka-Ching!!",
			"target0":"scenario-A",
			"opt1":"Ini tak beretika dan mungkin juga haram. Cuba fikir betul-betul dulu.",
			"target1":"scenario-B",
		},
		{
			"id":"scenario-A",
			"text":"<p>Kau mula merancang artikel kau. Apa yang kau perlu bagi tumpuan dulu?</p>",
			"img":"../img/story-2/A.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Herba atau penawar untuk melawan dari jangkitan Covid-19. Pasti akan dapatkan perhatian pak cik dan mak cik. Apa lah yang lagi teruk yang akan berlaku?",
			"target0":"scenario-A1",
			"opt1":"Menyamar dakwaan pihak kerajaan mengenai langkah-langkah keselamatan dan tempat-tempat awam “yang terjejas” oleh Covid-19. Mesti ni akan dapat perhatian orang ramai.",
			"target1":"scenario-A2",
		},
		{
			"id":"scenario-B",
			"text":"",
			"img":"../img/story-2/B.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":1,
			"opt0":"Apasal tak boleh? Kau perlukan duit ni $$",
			"target0":"scenario-A2",
			"opt1":"Kau faham maklumat palsu boleh mengakibatkan sesuatu yang buruk. Mungkin kau boleh menghasilkan kandungan yang tidak bahaya?",
			"target1":"scenario-A1",
		},
		{
			"id":"scenario-A1",
			"text":"<p>Untuk artikel pertama, kau petik <em>statement</em> daripada seorang doktor palsu yang mendakwa bahawa minum 5 gelas air lemon-bawang putih boleh melindungi diri daripada Covid telah mendapat perhatian orang ramai di alam maya.</p>",
			"img":"../img/story-2/A1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Permulaan yang bagus!",
			"target0":"scenario-A1_1",
		},
		{
			"id":"scenario-A1_1",
			"text":"<p>Bos kau hubungi dan mengucapkan tahniah kepada kau. Dia juga bagi beberapa nasihat untuk memastikan artikel tersebut terus viral.</p>",
			"img":"../img/story-2/A1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Yang mana satu kau nak cuba dulu?",
			"target0":"scenario-A1_2",
		},
		{
			"id":"scenario-A1_2",
			"text":"",
			"img":"../img/story-2/A1.png",
			"more":1,
			"info":"<p>Ada beberapa syarikat yang menjual <a href='https://www.nytimes.com/interactive/2018/01/27/technology/social-media-bots.html' target='_blank'> pengikut-pengikut media sosial palsu </a> dan <em>engagements</em> termasuk <a href='https://www.nytimes.com/2019/12/06/technology/fake-social-media-manipulation.html' target='_blank'> <em>Facebook likes</em> </a> dan <a href='https://www.nytimes.com/interactive/2018/08/11/technology/youtube-fake-view-sellers.html' target='_blank'> <em>YouTube views</em> </a> dalam harga yang sangat murah. Mereka upah beberapa pengendali untuk mengendali akaun palsu, mencipta <em>bots</em> automatik dalam jumlah yang besar, dan guna kemudahan yang lain untuk manipulasi media sosial demi untung. Beberapa pengendali menggunakan beberapa kaedah untuk menyebar berita palsu untuk <a href='https://theconversation.com/how-fake-accounts-constantly-manipulate-what-you-see-on-social-media-and-what-you-can-do-about-it-139610' target='_blank'> mempengaruhi pendapat umum </a>.Kau fikir kau boleh kenal pasti akaun palsu di media sosial? Apa kata, kau cuba  <a href='https://spotthetroll.org/' target='_blank'> quiz ni </a>!</p>",
			"optNum":1,
			"optImg":0,
			"opt0":"Kau libatkan satu perkhidmatan <em>online</em> yang menawarkan 1,000 saham syarikat Facebook dengan hanya USD$25. Kalau artikel kau dapat viral, senang lah kau nak tanggung kos.",
			"target0":"scenario-A1-1",
			"opt1":"Kau cipta akaun media sosial palsu dan menyamar sebagai doktor dan jururawat dari barisan hadapan untuk menyiarkan artikel tersebut.",
			"target1":"scenario-A1-2",
		},
		{
			"id":"scenario-A2",
			"text":"<p>Kau mula mencipta “berita Covid-19” agar bos kau boleh memuat naik ke ratusan laman web yang dah ada. Bos kau juga bagi kat kau beberapa tips.</p>",
			"img":"../img/story-2/A2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Yang mana satu kau suka?",
			"target0":"scenario-A2_1",
		},
		{
			"id":"scenario-A2_1",
			"text":"",
			"img":"../img/story-2/A2.png",
			"more":1,
			"info":"<p>Gambar yang digunakan dalam mesej palsu selalunya adalah gambar lama yang digunakan semula atau dimanipulasi untuk menipu orang. Nasib baik ada kaedah cepat dan mudah untuk memeriksa gambar. Anda boleh melakukan carian gambar terbalik pada gambar untuk mengetahui asal usul gambar tersebut. Cara ini dapat membantu anda memeriksa sama ada gambar lama atau dikongsi di luar konteks. Berikut adalah <a href='https://youtu.be/p5e9wTdAulA' target='_blank'> video tutorial </a> untuk mengenai carian imej terbalik.</p>",
			"optNum":1,
			"optImg":0,
			"opt0":"Cari di alam maya untuk gambar lama kakitangan perubatan atau pesakit. Gunakannya sebagai dakwaan palsu bahawa kes Covid dikesan dari sana.",
			"target0":"scenario-A1-2",
			"opt1":"Guna perisian grafik untuk mengubah suai laporan berita dan pengumuman-pengumuman kerajaan untuk mencipta SOPs palsu dan sekatan palsu.",
			"target1":"scenario-A1-1",
		},
		{
			"id":"scenario-A1-1",
			"text":"<p>Berita palsu kau yang pertama dah viral. Kau pun gunakan tips yang diberikan oleh bos kau mengenai lebih banyak artikel Covid-19 dan <em>web traffic</em> kau melonjak naik. Kau diberikan bayaran yang sangat lumayan.</p>",
			"img":"../img/story-2/A1-1.png",
			"more":1,
			"info":"<p>Seorang penulis berita palsu yang bekerja di <em>content farm</em> di Malaysia mendakwa bahawa dia menjana <a href='https://www.twreporter.org/a/information-warfare-business-disinformation-fake-news-behind-line-group-english' target='_blank'>ribuan dolar</a> sebulan semasa zaman kegemilangannya.</p><p>Perniagaan mencipta berita palsu mencetuskan <a href='https://www.buzzfeednews.com/article/craigsilverman/how-macedonia-menjadi-a-global-hub-for-pro-trump-misinfo#.hcRNEk6Ox ' target='_blank'> panik </a> di kalangan remaja di sebuah bandar kecil di Macedonia sebelum pilihan raya presiden Amerika Syarikat 2016. Seorang remaja di sana mendakwa dia memperoleh <a href='https://www.wired.com/2017/02/veles-macedonia-fake-news/' target='_blank'> puluhan ribu dolar </a> dalam beberapa bulan dari laman web pro-Trump yang mengeluarkan berita sensasionalis, yang benar-benar palsu.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Senang giler!",
			"target0":"scenario-A1-1_1",
		},
		{
			"id":"scenario-A1-1_1",
			"text":"<p>Semasa meraikan “kerjaya” baru kau, kau menerima amaran berita di telefon bimbit kau bahawa pasangan tua jatuh sakit parah setelah menggunakan ubat yang kau cadangkan dalam salah satu artikel kau. Kau berasa bersalah sedikit. Tapi bos kau call kau dan tawarkan satu pekerjaan yang lebih lumayan.</p>",
			"img":"../img/story-2/A1-1_1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Aku nak tau lagi!",
			"target0":"scenario-A1-1_2",
		},
		{
			"id":"scenario-A1-1_2",
			"text":"<p>Dia nak kau buat video <em>deepfake</em> yang menunjukkan ahli Parlimen tertentu “memberitahu” penyokongnya bahawa orang yang memakai topeng muka adalah pengecut dan takut mati. Kau mengesyaki ada udang disebalik batu - pesaing parti politik berada di belakang langkah ini.</p>",
			"img":"../img/story-2/A1-1_2.png",
			"more":1,
			"info":"<p><em>Deepfake</em> menggunakan teknik <em>artificial intelligence</em> dikenali sebagai <em>deep learning</em> untuk manipulasi atau mereka imej palsu. Mereka boleh letak <a href='https://youtu.be/cQ54GDm1eL0' target='_blank'> kata-kata dimulut ahli politik </a> atau biarkan anda membintangi di dalam filem kegemaran anda. Berikut adalah <a href='https://edition.cnn.com/videos/business/2020/12/25/queen-elizabeth-deepfake.cnn' target='_blank'> video <em>deepfake</em> </a> Queen Elizabeth II menarai di depan skrin TV pada hari Christmas. <em>Tools</em> dan <em>tutorials</em> wujud di alam maya untuk menunjukkan bagaimana <em>deepfakes</em> dicipta. Tolong jangan salah gunakannya!</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"So, kau nak ambik kerja ni atau tak?",
			"target0":"scenario-A1-1_3",
		},
		{
			"id":"scenario-A1-1_3",
			"text":"",
			"img":"../img/story-2/A1-1_2.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Apa salahnya? Lagipun, apa yang ahli politik pernah lakukan untuk anda sebelum ni?",
			"target0":"scenario-A1-1-1",
			"opt1":"Tolak sebab berita palsu yang kau cipta telah menyakitkan orang lain. Kau nak fokus kepada <em>content</em> yang kurang berbahaya.",
			"target1":"scenario-A1-1-2",
		},
		{
			"id":"scenario-A1-1-1",
			"text":"<p>Kau cari di alam maya untuk tutorial yang menunjukkan cara-cara untuk membuat video deepfake dan siapkan kerja yang sepatutnya. Walaupun dinafikan, MP disiasat oleh polis, dan orang ramai menuntut dia untuk meletak jawatan.</p>",
			"img":"../img/story-2/A1-1-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-1-1_1",
		},
		{
			"id":"scenario-A1-1-1_1",
			"text":"<p>Dia terus membuat laporan polis mengenai video tersebut. Tak lama kemudian, polis muncul di depan pintu rumah kau. Mereka telah menjejaki video tersebut asal daripada kau. Kau telah ditangkap dan disiasat. Lebih teruk lagi, ahli politik itu mendakwa anda atas sebab fitnah.</p>",
			"img":"../img/story-2/A1-1-1.png",
			"more":1,
			"info":"<p>Ratusan orang disyaki menyebar berita palsu telah disiasat pada tahun 2020 termasuk <a href='https://www.bernama.com/en/general/news_covid-19.php?id=1869002' target='_blank'> seorang perempuan </a> yang membuat dakwaan palsu mengenai sebuah pasaraya ditutup akibat Covid-19. Sehingga Oct 8, 2020, pihak berkuasa telah membuka hampir <a href='https://bernama.com/en/general/news_covid-19.php?id=1887864' target='_blank'> 300 siasatan </a> berkaitan dengan kesalahan tersebut dan 35 individu telah didakwa. Sebahagian besar daripada mereka disiasat di bawah Seksyen 233 Akta Komunikasi dan Multimedia 1998 dan Seksyen 505 (b) Kanun Keseksaan.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Habis",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-1-2",
			"text":"<p>Keesokan harinya, lebih ramai orang dikejarkan ke hospital disebabkan ubat palsu tu, dan beberapa orang dah mati. Walaupun artikel-artikel kau telah dijelaskan oleh laporan berita lain, mereka masih tersebar dan ramai orang masih mempercayainya.</p>",
			"img":"../img/story-2/A1-1-2.png",
			"more":1,
			"info":"<p>Pandemik Covid-19 telah memacu gelombang <a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'> perubatan tradisional palsu </a> dikongsi dalam alam maya. <a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'> <em>Scammer</em> </a> membanjiri media sosial dengan dakwaan penawar dan ujian palsu. Ramai orang dari pelbagai negara telah terbunuh atau jatuh sakit kerana mempercayai penawar yang tak ada bukti sah seperti <a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'> alkohol </a> dan <a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'> chloroquine </a>, ubat yang digunakan terutamanya untuk merawat malaria.</p><p>Lagi teruk adalah penularan kenyataan palsu lebih pantas dah luas berbanding kenyataan benar. Satu kajian selidik dari Massachusetts Institute of Technology (MIT) telah temui bahawa penularan berita palsu <a href='https://news.mit.edu/2018/study-twitter-false-news-travels-faster-true-stories-0308' target='_blank'> 6 kali lebih pantas </a> berbanding berita sebenar. Sentiasa semak sumber maklumat walaupun dikongsi oleh ahli keluarga dan/atau sahabat handai.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-1-2_1",
		},
		{
			"id":"scenario-A1-1-2_1",
			"text":"<p>Tidak lama kemudian, bos kau memberitahu kau bahawa semua kandungan laman web telah ditutup tapi dia akan menghubungi kau sekali lagi setelah dia aktifkan semula.</p>",
			"img":"../img/story-2/A1-1-2.png",
			"more":1,
			"info":"<p>Syarikat media sosial seperti Facebook dan Twitter kerap mengeluarkan <a href='https://www.bbc.com/news/business-53018455' target='_blank'> akaun-akaun palsu </a> dan <a href='https://www.reuters.com/article/cyber-disinformation-facebook-twitter-idINKBN26T2XF' target='_blank'> memutuskan rangkaian palsu </a>. Facebook telah memutuskan sekitar 4.5 billion akaun-akaun palsu pada sembilan bulan pertama pada tahun 2020 dan lagi 5.4 billion akaun-akaun palsu pada tahun 2019. Walau bagaimanapun, tindakan berikut masih <a href='https://www.nytimes.com/2020/12/08/technology/why-cant-the-social-networks-stop-fake-accounts.html' target='_blank'> gagal </a> untuk hentikan lebih banyak lagi akaun-akaun palsu daripada dicipta.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Tapi...",
			"target0":"scenario-A1-1-2_2",
		},
		{
			"id":"scenario-A1-1-2_2",
			"text":"<p>Kau kata kat dia yang kau dah tak berminat lagi untuk menjajakan berita palsu. Kau berasa lega tapi kau tahu akibat perbuatan kau lakukan pada orang lain telah terlambat.</p>",
			"img":"../img/story-2/A1-1-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-2",
			"text":"<p>Berita palsu pertama kau menjadi viral. Kau juga menggunakan petua lain dari bos anda mengenai lebih banyak artikel Covid-19 dan <em>web traffic</em> melonjak naik! Setelah mengeluarkan ratusan artikel selama sebulan, kau menerima cek yang besar.</p>",
			"img":"../img/story-2/A1-1.png",
			"more":1,
			"info":"<p>Seorang penulis “berita palsu” yang bekerja di <em>content farm</em> di Malaysia mendakwa bahawa dia menjana <a href='https://www.twreporter.org/a/information-warfare-business-disinformation-fake-news-behind-line-group-english' target='_blank'>ribuan dolar</a> sebulan semasa zaman kegemilangannya.</p><p>Perniagaan mencipta berita palsu mencetuskan <a href='https://www.buzzfeednews.com/article/craigsilverman/how-macedonia-menjadi-a-global-hub-for-pro-trump-misinfo#.hcRNEk6Ox' target='_blank'> panik </a> di kalangan remaja di sebuah bandar kecil di Macedonia sebelum pilihan raya presiden Amerika Syarikat 2016. Seorang remaja di sana mendakwa dia memperoleh <a href='https://www.wired.com/2017/02/veles-macedonia-fake-news/' target='_blank'> puluhan ribu dolar </a> dalam beberapa bulan dari laman web pro-Trump yang mengeluarkan berita sensasionalis, yang benar-benar palsu.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Ka-Ching!",
			"target0":"scenario-A1-2_1",
		},
		{
			"id":"scenario-A1-2_1",
			"text":"<p>Sekarang, bos kau kata yang ada pelanggan upah dia untuk menyebarkan konspirasi teori virus Covid-19 yang dicipta dari makmal di satu negara sebagai senjata bio, dan ia dah dilepaskan. Kerja kau adalah untuk menterjemahkan <em>content</em> tersebut dalam bahasa tempatan dan sebarkan ke seluruh rangkaian akaun-akaun palsu yang kau dah buat.</p>",
			"img":"../img/story-2/A1-1_2.png",
			"more":1,
			"info":"<p>Maklumat palsu (jugak dikenali sebagai <em>misinformation</em>) yang membawa niat buruk atau yang membawa niat untuk mempengaruhi orang dikenali sebagai <em>disinformation</em>. Kempen propaganda oleh kerajaan atau yang lain-lain kadang kala guna maklumat yang mengelirukan atau maklumat bias atau fakta yang dimanipulasi untuk menyerang pesaing mereka sambil mempromosi agenda mereka. Negara-negara termasuk Russia, China dan Amerika Syarikat telah dituduh bersalah akibat melancarikan operasi kempen-kempen tersebut. Pada ketika pandemik Covid-19, siasatan telah menunjuk bahawa <a href='https://www.theatlantic.com/politics/archive/2020/05/china-disinformation-propaganda-united-states-xi-jinping/612085/' target='_blank'> media kerajaan negeri China </a> dan <a href='https://www.bloomberg.com/news/articles/2020-05-12/china-s-disinformation-campaign-targets-virus-and-businessman' target='_blank'> akaun-akaun palsu </a> beroperasi dari tanah besar China dengan menyebarkan konspirasi teori mengenai asal usul coronavirus.</p>",
			"optNum":0,
			"optImg":1,
			"opt0":"Hmm...",
			"target0":"scenario-A1-2_2",
		},
		{
			"id":"scenario-A1-2_2",
			"text":"<p>Kau syak ini adalah sebagian daripada kempen palsu dari kuasa asing. Kau nak ambik kerja ni atau tak?</p>",
			"img":"../img/story-2/A1-1_2.png",
			"more":0,
			"info":"",
			"optNum":1,
			"optImg":0,
			"opt0":"Tak ada sebab untuk menolak kerana gaji yang ditawarkan jauh lebih baik berbanding mereka cipta kandungan viral sendiri.",
			"target0":"scenario-A1-2-1",
			"opt1":"Tolak tawaran secara sopan kerana kau mula berasa bimbang sekiranya kau akan menimpa masalah besar oleh pihak berkuasa.",
			"target1":"scenario-A1-2-2",
		},
		{
			"id":"scenario-A1-2-1",
			"text":"<p>Maklumat yang kau sebarkan telah sampai ke jutaan orang dari serata dunia. Walau bagaimanapun, ia juga menarik perhatian pihak berkuasa dan pihak media. Salah satu wartawan cuba menjejaki anda dan cuba mendedahkan anda.</p>",
			"img":"../img/story-2/A1-2-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Alamak!",
			"target0":"scenario-A1-2-1_1",
		},
		{
			"id":"scenario-A1-2-1_1",
			"text":"<p>Kau sendiri tahu yang kau perlu hentikan segera sebelum ada orang datang mengetuk pintu kau. Dengan itu, kau terus lesap kan diri secepat mungkin serta tutup kesemua akaun alam maya, hentikan kesemua saluran-saluran komunikasi dan pekerjaan kau, dan pindah semula ke rumah mak bapak kau. Kau betul-betul menganggur sekarang dan masa depan kau kelihatan suram.</p>",
			"img":"../img/story-2/A1-2-1.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-A1-2-2",
			"text":"<p>Pada minggu yang berikutnya, kau terserempak konspirasi teori yang itular di alam maya. Nampak gayanya, ada orang lain yang telah ambil pekerjaan tersebut.</p>",
			"img":"../img/story-2/A1-2-2.png",
			"more":0,
			"info":"",
			"optNum":0,
			"optImg":1,
			"opt0":"Seterusnya",
			"target0":"scenario-A1-2-2_1",
		},
		{
			"id":"scenario-A1-2-2_1",
			"text":"<p>Pada satu hari, bos kau hubungi untuk memberitahu kau yang laman web dia ditutup setelah didedah oleh seorang wartawan tapi dia akan hubungi kau semula selepas dia cuba hidupkan laman webnya semula. Kau bagitau dia yang kau dah tak berminat dengan kerja ni lagi. Kau berasa lega.</p>",
			"img":"../img/story-2/A1-2-2.png",
			"more":1,
			"info":"<p>Syarikat media sosial seperti Facebook dan Twitter kerap mengeluarkan <a href='https://www.bbc.com/news/business-53018455' target='_blank'> akaun-akaun palsu </a> dan <a href='https://www.reuters.com/article/cyber-disinformation-facebook-twitter-idINKBN26T2XF' target='_blank'> memutuskan rangkaian palsu </a>. Facebook telah memutuskan sekitar 4.5 billion akaun-akaun palsu pada sembilan bulan pertama pada tahun 2020 dan lagi 5.4 billion akaun-akaun palsu pada tahun 2019. Walau bagaimanapun, tindakan berikut masih <a href='https://www.nytimes.com/2020/12/08/technology/why-cant-the-social-networks-stop-fake-accounts.html' target='_blank'> gagal </a> untuk hentikan lebih banyak lagi akaun-akaun palsu daripada dicipta.</p>",
			"optNum":0,
			"optImg":0,
			"opt0":"Tamat",
			"target0":"scenario-end",
		},
		{
			"id":"scenario-end",
			"text":"<p>Semasa permulaan Covid-10 serta dibanjiri dengan maklumat di alam maya, perasaan takut, bimbang dan kekurangan kesedaran literasi maklumat mampu menyebabkan para pengguna internet senang percayai terhadap apa-apa yang kelihatan berwibawa tanpa mengambil lebih banyak tenaga untuk mengesahkan kesahihannya. Pihak-pihak yang tidak bertanggungjawab mampu menjana pendapatan daripada menyebarkan berita palsu di alam maya. Dengan mempelajari kemahiran asas mengenal pasti berita palsu dan mengesahkan kesahihan maklumat dapat mengelakkan diri anda menjadi mangsa.</p><p>Main dua watak yang lain untuk mengetahui lebih lanjut mengenai penularan berita palsu dari perspektif seorang mangsa dan seorang penyebar berita palsu yang tidak sengaja.</p>",
			"endLinks":[
				"<a href='https://fivethirtyeight.com/features/why-a-gamer-started-a-web-of-disinformation-sites-aimed-at-latino-americans/' target='_blank'>Why A Gamer Started A Web Of Disinformation Sites Aimed At Latino Americans</a>",
				"<a href='https://coconuts.co/kl/news/malaysia-man-criticized-after-naming-black-man-number-one-suspect-in-us-shooting/' target='_blank'>Malaysia man criticized after naming Black man ‘number one suspect’ in US shooting</a>",
				"<a href='https://www.twreporter.org/a/information-warfare-business-disinformation-fake-news-behind-line-groups-english' target='_blank'>The Content Mill Empire Behind Online Disinformation in Taiwan</a>",
				"<a href='https://www.bbc.com/future/article/20190528-i-was-a-macedonian-fake-news-writer' target='_blank'>‘I was a Macedonian fake news writer’</a>",
				"<a href='https://www.nytimes.com/interactive/2018/01/27/technology/social-media-bots.html' target='_blank'>The Follower Factory</a>",
				"<a href='https://www.nytimes.com/interactive/2018/08/11/technology/youtube-fake-view-sellers.html' target='_blank'>The Flourishing Business of Fake YouTube Views</a>",
				"<a href='https://edition.cnn.com/videos/business/2020/12/25/queen-elizabeth-deepfake.cnn' target='_blank'>Watch 'deepfake' Queen deliver alternative Christmas speech</a>",
				"<a href='https://www.theatlantic.com/politics/archive/2020/05/china-disinformation-propaganda-united-states-xi-jinping/612085/' target='_blank'>How China Is Planning to Win Back the World</a>",
			]
		}
	]	
];